### PR TITLE
fix: Tech Admin top bar

### LINKED ISSUE #1086: Tech Admins locked out by new topbar
**Describe the bug**

we have a problem with the new UI and tech_admin - they don't see the sidebar, and navigation "back" or "sandwich" don't do anything..

**To Reproduce**
1.  Login as Tech Admin
2. Navigate
3.

**Info on:**
Username:
Role: Tech Admin
Environment used:
Instance code
Browser:

### PR DESCRIPTION
**Pull request by eduardoliron**
## Context 

Tech Admins got locked out by new topbar

## Checklist

- [x] Tested manually 
- [ ] Passed automatic tests 
- [x] GitHub issue linked 
- [x] Changelist updated
- [x] Backward and forward compatible with [aula-backend/releases](https://github.com/aula-app/aula-backend/releases) 
- [x] Doesn't need update in the database or BE 
- [x] Must be deployed ASAP (HOTFIX)
- [ ] Needs update of [docs.aula.de](https://docs.aula.de/) ([repo](https://github.com/leonard-haas/docs_aula))

### CODE REVIEW

File: src/layout/PrivateLayout/TopBar/TechTopBar.tsx [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+            alt={t('app.name.logo')}
+            role="img"
+            className="h-8 w-auto"
+          />
+        </div>
+        <div className="flex-1 flex items-center justify-center h-full overflow-hidden">
+          {t('ui.navigation.adminPanel')}
+        </div>
+        <IconButton onClick={onLogout} aria-label={t('auth.logout')}>
+          <Icon type="logout" size="1.5rem" aria-hidden="true" />
```
Comment (nikola-maric-aula) [inline src/layout/PrivateLayout/TopBar/TechTopBar.tsx:36]: nitpick: could we also add a tooltip?

**Review by nikola-maric-aula — APPROVED** [review]

File: src/layout/PrivateLayout/LayoutContainer.tsx [hunk 2]
```diff
@@ -62,7 +63,11 @@ const LayoutContainer: FunctionComponent<PropsWithChildren> = ({ children }) =>
   return (
     <div className="flex flex-col h-dvh w-full overflow-hidden">
       <SkipNavigation mainContentId="main-content" />
-      <TopBar mobileMenuOpen={mobileMenuOpen} onToggleMobileMenu={toggleMobileMenu} menuButtonRef={menuButtonRef} />
+      {checkPermissions('system', 'hide') ? (
+        <TechTopBar mobileMenuOpen={mobileMenuOpen} onToggleMobileMenu={toggleMobileMenu} menuButtonRef={menuButtonRef} />
```
Comment (nikola-maric-aula) [inline src/layout/PrivateLayout/LayoutContainer.tsx:67]: note: the new top bar doesn't have **language** settings and **dark mode** and that stuff.. i'd say we can **accept this as not implemented and go on**, since we're anyways planning to sunset tech_admin role..

**Review by aivuk — APPROVED** [review]

File: src/layout/PrivateLayout/TopBar/TechTopBar.tsx (hunk 1 above)
Comment (eduardoliron) [reply src/layout/PrivateLayout/TopBar/TechTopBar.tsx:36]: done

File: src/layout/PrivateLayout/LayoutContainer.tsx (hunk 2 above)
Comment (eduardoliron) [reply src/layout/PrivateLayout/LayoutContainer.tsx:67]: Done

**Review by nikola-maric-aula — APPROVED** [review]
