### PR TITLE
Fix: update voting and liking count on user interaction

### LINKED ISSUE #1039: A user need to reload the page to like bar chart increase
**Describe the bug**
A user need to reload the page to see that the like he gives to an idea get added to the bar chart

**To Reproduce**
1. Like an idea
2. look at bar hart
3. reload page

**Info on:**
Username:
Role:
Environment used:
Instance code
Browser:

Image
Image
Image

### PR DESCRIPTION
**Pull request by eduardoliron**
## Context 

User needed to reload the page to like bar chart increase

## Checklist

- [x] Tested manually 
- [ ] Passed automatic tests 
- [x] GitHub issue linked 
- [x] Changelist updated
- [x] Backward and forward compatible with [aula-backend/releases](https://github.com/aula-app/aula-backend/releases) 
- [x] Doesn't need update in the database or BE 
- [ ] Must be deployed ASAP (HOTFIX)
- [ ] Needs update of [docs.aula.de](https://docs.aula.de/) ([repo](https://github.com/leonard-haas/docs_aula))

### CODE REVIEW

**Review by aivuk — CHANGES_REQUESTED** [review]
I think that we must always write a test with a fix like this PR or to a new feature.

File: src/components/Buttons/LikeButton/LikeButton.tsx [hunk 1]
```diff
@@ -24,13 +26,30 @@ const LikeButton = forwardRef<HTMLButtonElement, Props>(({ item, disabled }, ref
...
 
+  const updateLikeStatus = (newStatus: boolean) => {
+    setLikeStatus(newStatus);
+    if (onChange) {
+      onChange(Number(newStatus) - Number(liked));
+    }
+  };
+
   const toggleLike = async () => {
+    updateLikeStatus(!likeStatus);
```
Comment (nikola-maric-aula) [inline src/components/Buttons/LikeButton/LikeButton.tsx:38]: suggestion: while network call is executing, show "in progress" status (something indicating operation is in progress 🛞♻️) instead of `${item.sum_likes + Number(likeStatus) - Number(liked)}`

background: i see that with this change we're trying to be more responsive in displaying the effect of the LikeButton click, but that might falsely indicate the like has been saved on the server, and the user can close the browser page before it actually happens..

File: src/components/Idea/VotingResults/VotingResults.tsx [hunk 2]
```diff
@@ -84,9 +85,11 @@ const VotingResults: React.FC<Props> = ({ idea, quorum, onReload }) => {
             <Typography variant="h3">
               {idea.is_winner === 1
                 ? t(`scopes.ideas.winner`)
-                : quorumPassed()
-                  ? t(`scopes.ideas.approved`)
-                  : t(`scopes.ideas.rejected`)}
+                : !quorum
```
Comment (nikola-maric-aula) [inline src/components/Idea/VotingResults/VotingResults.tsx]: suggestion: `!quorum` will be true when `quorum === 0`, but that's a proper value, right?

```suggestion
                : quorum !== undefined
```

**Review by nikola-maric-aula — COMMENTED** [review]
lgtm, but one small suggestion, and i agree we should have a test..

**Comment by nikola-maric-aula** [comment]
e2e can come after https://github.com/aula-app/aula-frontend/pull/1060

File: src/components/Buttons/LikeButton/LikeButton.tsx (hunk 1 above)
Comment (eduardoliron) [reply src/components/Buttons/LikeButton/LikeButton.tsx:38]: What we are doing now is, we confirm the like, but of an error returns, we roll back... I think this will feel much more finctional for the user.

Comment (eduardoliron) [reply src/components/Buttons/LikeButton/LikeButton.tsx:38]: I will make it disabled while pending

**Review by aivuk — APPROVED** [review]

File: src/components/Buttons/LikeButton/LikeButton.tsx [hunk 3]
```diff
@@ -24,13 +27,27 @@ const LikeButton = forwardRef<HTMLButtonElement, Props>(({ item, disabled }, ref
...
+      const response = await (likeStatus
+        ? isIdea ? removeIdeaLike(item.hash_id) : removeCommentLike(item.id)
+        : isIdea ? addIdeaLike(item.hash_id) : addCommentLike(item.id));
+      if (response.error) {
+        updateLikeStatus(!likeStatus); // Revert like status if API call fails
+        dispatch({ type: 'ADD_POPUP', message: { message: t('errors.failed'), type: 'error' } });
+      }
+    } finally {
+      setIsPending(false);
     }
```
Comment (nikola-maric-aula) [inline src/components/Buttons/LikeButton/LikeButton.tsx:50]: @eduardoliron there's an issue here, if the server responds without "error" field in the response, but the request fails due to "success: false", we're not reverting to old value..

Image

Comment (nikola-maric-aula) [reply src/components/Buttons/LikeButton/LikeButton.tsx:50]: converted to an issue: https://github.com/aula-app/aula-frontend/issues/1167
