### PR TITLE
fix: stop requesting `/api/files/` for non-existent avatars

### LINKED ISSUE #590: [FE] Remove attempt to fetch `//files`
**Describe the bug**
Seems like FE attempts to fetch `${baseUrl}/files/` pretty regularly when logged in (Profile page, opening Wilde-Ideen phase of a Room). I believe it is attempting to fetch the avatar of the user without one. We should avoid fetching it in case User doesn't have a profile picture.

**To Reproduce
1. Open dev console, network tab.
2. Log in.
3. Observe 403 on `/files/`.

P.S. It's good news we don't leak content of the `/files/` at least :D

**Info on:**
Username: nikola
Role: admin
Environment used: devel
Browser: firefox

### PR DESCRIPTION
**Pull request by nikola-maric-aula**
## Context 

Fixes https://github.com/aula-app/aula-frontend/issues/590

## Checklist

- [x] Tested manually 
- [x] Passed automatic tests 
- [ ] GitHub issue linked 
- [ ] Changelist updated
- [x] Backward and forward compatible with [aula-backend/releases](https://github.com/aula-app/aula-backend/releases) 
- [x] Doesn't need update in the database or BE 
- [ ] Must be deployed ASAP (HOTFIX)
- [ ] Needs update of [docs.aula.de](https://docs.aula.de/) ([repo](https://github.com/leonard-haas/docs_aula))

### CODE REVIEW

File: src/components/UserAvatar/UserAvatar.tsx [hunk 1]
```diff
@@ -38,7 +38,7 @@ const UserAvatar = ({ id, size = 32, sx, ...restOfProps }: Props) => {
         ...sx,
       }}
       alt={t('user.avatar', { id: id })}
-      src={`${api_url}/api/files/${code}/${userAvatar}` || ''}
+      src={userAvatar ? `${api_url}/api/files/${code}/${userAvatar}` : ''}
```
Comment (nikola-maric-aula) [inline src/components/UserAvatar/UserAvatar.tsx:41]: @eduardoliron does this make sense?

Comment (eduardoliron) [reply src/components/UserAvatar/UserAvatar.tsx:41]: Yep

**Review by eduardoliron — APPROVED** [review]
