### PR TITLE
fix: display warningerror when killswitch version is not matched

### LINKED ISSUE #1017: display warning/error when killswitch version is not matched
In case FE version is lower than what our BE API requires ("minimum") or recommends ("recommended"), we should display an error or a popup warning message on startup. We don't want to be super annoying, so i'd keep this only on app startup.

In case of error (minimum version not met), we shouldn't allow the user to continue using the app because that can potentially create corrupt state in the BE/database or due to security concerns.

We should think of a way to make sure FE occasionally rechecks - perhaps the easiest is that: when this error appears, wait for user to dismiss it, and then close the app. That way, the user will have to reopen the app again, and we will perform new version check on startup. I assume on web we shouldn't close the tab, but simply invoke a (hard) refresh so that FE js assets are updated.

Additionally, FE should be aware that BE can at any moment (to any request) respond with 426 HTTP status code and this should be interpreted in the same way as if the "minimum required" version is not being met (display error, and when user acknowledges the error then logout the user and "lock" the app until the minimum version is fulfilled).

### PR DESCRIPTION
**Pull request by eduardoliron**
## Context 

Fix bugs on the feature:

1. sometimes there's several warning messages popping up, when recommended version is not met, although i haven't been able to replicate this issue very consistently
2. when logging in, we should always check the version regardless of the cache timeout (i tested: while user is logged in i change BE required version to very high, i log out the user and log in another user, and no error appeared)

## Checklist

- [x] Tested manually 
- [ ] Passed automatic tests 
- [x] GitHub issue linked 
- [x] Changelist updated
- [x] Backward and forward compatible with [aula-backend/releases](https://github.com/aula-app/aula-backend/releases) 
- [x] Doesn't need update in the database or BE 
- [ ] Must be deployed ASAP (HOTFIX)
- [ ] Needs update of [docs.aula.de](https://docs.aula.de/) ([repo](https://github.com/leonard-haas/docs_aula))

### CODE REVIEW

File: src/hooks/useOutdatedGuard.ts [hunk 1]
```diff
@@ -64,7 +74,13 @@ export const useOutdatedGuard = (refreshKey?: string): OutdatedState => {
         if (recommendedVersion && recommendedVersion !== 'unknown') {
           const belowRecommended = isVersionBelowRecommended(currentVersion, recommendedVersion);
           setState((prev) => ({ ...prev, isBelowRecommended: belowRecommended }));
-          if (belowRecommended && !outdated) {
+
+          // Check if popup should be shown: either never shown, or shown more than 12h ago
+          const shouldShowPopup =
+            !popupShownRef.current ||
+            (now - popupShownRef.current.timestamp > POPUP_SHOWN_TTL_MS);
```
Comment (nikola-maric-aula) [inline src/hooks/useOutdatedGuard.ts:81]: suggestion: we can move this const around 15 lines up, before we call BE `versionsRequest()`, because if we already shown the popup recently, then we can skip the BE call and the rest of the function..

Comment (nikola-maric-aula) [reply src/hooks/useOutdatedGuard.ts:81]: ah, no sorry.. the "minimum" version could've changed in the meantime and we wouldn't catch it if we rely on the recency of the popup only..

**Review by nikola-maric-aula — APPROVED** [review]
